[programs.localnet]
anchor_escrow = "J5fjkFW5nrUuzD4eMD6c1ZS765KvMLyk1dpMm6aac2Nf"

[provider]
cluster = "http://127.0.0.1:8899"
#cluster="https://api.testnet.solana.com"
#cluster = "https://api.devnet.solana.com "
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
